"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000

format = """
[╭╴](#ff5990)\
$os\
$username\
[@](#7088ff)\
$hostname\
$jobs\
$directory\
$sudo\
$cmd_duration\
$bun\
$dart\
$java\
$kotlin\
$rust\
$fill\

$status\
$localip\
$battery\
$time
[╰⎯](#ff5990)\
$character
"""

[character]
success_symbol = '[#](bold #ff5990)'
error_symbol = '[#](bold #ff5990)'
vimcmd_symbol = '[](bold turquoise)'

[os]
disabled = false
format = '[$symbol]($style)'
style = 'bold #ff5990'

[os.symbols]
Windows = ' '
Arch = ''
Android = ' '
Debian = ' '
FreeBSD = ' '
NetBSD = ' '
OpenBSD = ' '
Macos = '󰀵'
Unknown = '󰠥'

[username]
disabled = false
format = ' (black bold)[$user]($style)'
show_always = true
style_user = 'bold #2BB7FB'
style_root = 'bold #ff5990'

[hostname]
disabled = false
format = '[$hostname ]($style)'
ssh_only = false
style = 'bold #2BB7FB'

[jobs]
format = '[$symbol$number]($style) '
style = 'bold #83e6ff'
symbol = '[▶](#83e6ff)'

[directory]
format = '[$path]($style)[$read_only ]($read_only_style)'
home_symbol = '~'
read_only = '  '
style = ' #83e6ff'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[sudo]
disabled = false
format = '[\[$symbol\] ]($style)'
style = 'bold #ff5990'
symbol = '⚡'

[cmd_duration]
disabled = false
format = '[ $duration]($style) '
style = 'dimmed #cc8afc'

[bun]
format = '[$symbol(${version} )]($style)'
style = 'dimmed #83e6ff'
symbol = ' '

[dart]
format = '[$symbol(${version} )]($style)'
style = 'dimmed #83e6ff'
symbol = ' '

[java]
format = '[$symbol(${version} )]($style)'
style = 'dimmed #83e6ff'
symbol = ' '

[kotlin]
format = '[$symbol(${version} )]($style)'
style = 'dimmed #83e6ff'
symbol = ' '

[rust]
format = '[$symbol(${version} )]($style)'
style = 'dimmed #83e6ff'
symbol = ' '

[fill]
symbol = ' '

[status]
disabled = false
failure_style = 'bold #ff5990'
format = '[$symbol\[$status\] ]($style)'
symbol = "\\(╯°□°）╯"

[localip]
disabled = false
format = '[$localipv4]($style)[  ](#cc8afc)'
style = 'dimmed #7088ff'
ssh_only = false

[time]
disabled = false
format = '[$time]($style)'
style = '#83e6ff'
time_format = '%I:%M:%S'
use_12hr = true
utc_time_offset = 'local'

[vagrant]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true