"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000

format = """
[╭╴](#7088ff)\
$os\
$username\
[@](#7088ff)\
$hostname\
$jobs\
$directory\
$cmd_duration\
$bun\
$dart\
$java\
$kotlin\
$rust\
$fill\

$status\
$package\
$sudo\
$localip\
$battery\
$time
[╰⎯](#7088ff)\
$character
"""

[character]
success_symbol = '[\$](bold #cc8afc)'
error_symbol = '[\$](bold #cc8afc)'
vimcmd_symbol = '[](bold turquoise)'
#success_symbol = '[#](bold #ff5990)'
#error_symbol = '[#](bold #ff5990)'

[os]
disabled = false
format = '[$symbol]($style)'
style = 'bold #7088ff'

[os.symbols]
Windows = ' '
Arch = '󰣇'
Android = ' '
Debian = ' '
FreeBSD = ' '
NetBSD = '󰉀 '
OpenBSD = ' '
Macos = '󰀵'
Unknown = '󰠥'

[username]
disabled = false
format = ' (black bold)[$user]($style)'
show_always = true
style_user = 'bold #2BB7FB'
style_root = 'bold #ff5990'

[hostname]
disabled = false
format = '[$hostname ]($style)'
ssh_only = false
style = 'bold #2BB7FB'

[jobs]
format = '[$symbol$number]($style) '
style = 'bold #83e6ff'
symbol = '[▶](#83e6ff)'

[directory]
format = '[$path]($style)[$read_only ]($read_only_style)'
home_symbol = '~'
read_only = '  '
style = 'italic #83e6ff'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[cmd_duration]
disabled = false
format = '[ $duration]($style) '
style = 'dimmed #cc8afc'

[bun]
format = '[$symbol(${version} )]($style)'
style = 'italic dimmed #83e6ff'
symbol = ' '

[dart]
format = '[$symbol(${version} )]($style)'
style = 'italic dimmed #83e6ff'
symbol = ' '

[java]
format = '[$symbol(${version} )]($style)'
style = 'italic dimmed #83e6ff'
symbol = ' '

[kotlin]
format = '[$symbol(${version} )]($style)'
style = 'italic dimmed #83e6ff'
symbol = ' '

[rust]
format = '[$symbol(${version} )]($style)'
style = 'italic dimmed #83e6ff'
symbol = ' '

[fill]
symbol = ' '

# SEPARATE

[status]
disabled = false
failure_style = 'bold #ff5990'
format = '[$symbol\[$status\] ]($style)'
symbol = "\\(╯°□°）╯"

[package]
disabled = false
format = '[$version ]($style)'
style = 'italic dimmed #83e6ff'

[sudo]
disabled = false
format = '[\[$symbol\] ]($style)'
style = 'bold #ff5990'
symbol = ''

[localip]
disabled = false
format = '[$localipv4]($style)[ 󰋑  ](#cc8afc)'
style = 'italic dimmed #7088ff'
ssh_only = false

[battery]
format = '[ $percentage $symbol]($style)'
charging_symbol = '[↑](italic bold green)'
discharging_symbol = '↓'

[[battery.display]]
threshold = 20
style = 'italic bold red'

[[battery.display]]
threshold = 60
style = 'italic dimmed bright-purple'

[[battery.display]]
threshold = 70
style = 'italic dimmed yellow'

[time]
disabled = false
format = '[$time]($style)'
style = 'italic #83e6ff'
time_format = '%I:%M:%S'
use_12hr = true
utc_time_offset = 'local'

[vagrant]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true