$LANG = 'en_US.UTF-8'
$LC_ALL = 'en_US.UTF-8'
$EDITOR='nvim'
$VISUAL='nvim'
$COLORTERM = 'truecolor'
$VC_BRANCH_TIMEOUT = 0.05
$HISTCONTROL='ignoredups,ignorespace'
$TERMINAL = 'rio'
$GPG_TTY = `tty`
$FOREIGN_ALIASES_SUPPRESS_SKIP_MESSAGE = True
$COLOR_INPUT = True
$COLOR_RESULTS = True
$INDENT = '  '
$XONSH_HISTORY_BACKEND = 'sqlite'