#!/bin/zsh
# shellcheck disable=SC1071

GREETING = '(/>w<)/ ...'

while :; do
  PID = $(tmux list-panes -F "#{?pane_active,#{pane_pid},}")
  while :; do
    tty=$(ps -p $PID -o tty= | xargs)
    tty=${tty#/dev/}
    TPGID=$(ps -t $tty -o tpgid | tail -n 1 | xargs)
    [ -z "$TPGID" ] || [ "$TPGID" = "$PID" ] && break
    PID=$TPGID
  done
  wezterm cli set-window-title "${GREETING} $(ps -o command= -p $PID)"
  sleep 0.2
done
